version: "3"

services:
  php:
    container_name: vmap_generator_php
    restart: always
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 5173:5173
    volumes:
      - vendor:/var/www/vendor
      - .:/var/www:cached
  nginx:
    container_name: vmap_generator_nginx
    image: nginx
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8001:80
    volumes:
      - vendor:/var/www/vendor
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  # db:
  #   container_name: vmap_generator_mysql
  #   image: mysql:8.1
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - /var/lib/mysql:/var/lib/mysql
  #     - .docker/logs:/var/log/mysql
  #     - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - .docker/db/sql:/docker-entrypoint-initdb.d
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
volumes:
  vendor:
